### ISSUE TITLE
Core extension concerns (calc_x branch)

### ISSUE THREAD

**Issue by Ptico** [grempe/sirp#1]
Hi Glenn! First of all, thank you for your great work on adopting scrypt, i spent hours to investigate possibility to do this without any luck, so well done!

I have some concerns about `rubype` gem which extends core objects and based on C extension (which is not that bad, but I don't trust C-exts not well tested in different environments).
If you agree with my points, I will be happy to create a PR with something like this gem https://github.com/egonSchiele/contracts.ruby – which is pure ruby and does not pollute core objects

**Comment by grempe** [comment]
Thanks very much for the tip and the suggestion.  I had not seen the contracts gem before and I like its semantics better than `rubype`. I was less concerned about the C extension, but that probably makes for good hygiene to reduce the use of C extensions when possible.

My implementation is bare-bones and probably only scrapes the surface of what the capable contracts gem can do. Feel free to chime in with suggestions or pull requests to enhance or fix.

Also, keep in mind, this is still pre-release software and it is currently only compatible with itself. :-)

Thanks!
