### ISSUE TITLE
Bug : proof must have the required hash with rails 5.2

### ISSUE THREAD

**Issue by antonin-arquey** [grempe/sirp#7]
Hello,

After upgrading to rails 5.2, we ran into an issue with this gem.
The srp verifier could not handle hash with strings key anymore. 
(Error : `proof must have required hash keys`)

We had to change 

`srp.verify_session(@server_proof, @client_proof)`

to

`srp.verify_session(@server_proof.deep_symbolize_keys, @client_proof)`

It seems that the Hashie symbolize keys line is not doing its job : 
https://github.com/grempe/sirp/blob/7337274f46d279403d7c76ce722fccb29f104dae/lib/sirp/verifier.rb#L89-L90

**Comment by grempe** [comment]
Thanks for reporting and sorry for the extreme delay. It should be resolved now in my last commit.
